### ISSUE TITLE
[Question] PropType Warning Messages

### ISSUE THREAD

**Issue by Michaelprothero** [zillow/redux-inputs#16]
Hello!

First off, great module has worked extremely well for all our use cases.
Quick question, I am seeing failed PropType messages in the debug console for the following props:
- dispatchChange
- _id

I couldn't find anywhere specific in the docs that these should be passed to ReduxInputsWrapper and was under the impression _id would be handled by the library when passing an id prop.

If you could point me in the right direction that would be great, apologies if i've missed anything obvious.

Thanks!

**Comment by stonebk** [comment]
@Michaelprothero this looks like a bug to me -- we'll work on a fix!

**Comment by kazooie** [comment]
`dispatchChange` and `_id` should be provided in `inputProps` from [connectWithInputs](https://github.com/zillow/redux-inputs/blob/master/docs/connectWithInputs.md). Passing an `id` prop yourself is just to override the default generated `_id`, and shouldn't be necessary.

**Comment by stonebk** [comment]
Also, see the example at the bottom here: https://github.com/zillow/redux-inputs/blob/master/docs/ReduxInputsWrapper.md
